### ISSUE TITLE
Cannot convert cache to PSR-6 cache

### ISSUE THREAD

**Issue by ariesprodesign** [doctrine/persistence#179] opened 2021-05-15 21:25 UTC
Hi. Since version 2.2.0 I have a bug:

Cannot convert cache to PSR-6 cache

  Type: BadMethodCallException
  File: Packages/Libraries/doctrine/persistence/lib/Doctrine/Persistence/Mapping/AbstractClassMetadataFactory.php
  Line: 91

**Comment by greg0ire** [comment] 2021-05-15 21:36
https://github.com/doctrine/persistence/blob/08d3e6e666de85c7748fa27bfd63bb15ac29eab2/lib/Doctrine/Persistence/Mapping/AbstractClassMetadataFactory.php#L90-L92

It means `$cacheDriver` is not an instance of `CacheProvider`. What is it then?

**Comment by ariesprodesign** [comment] 2021-05-16 00:14
Thank you for your prompt reply. Sure I know what the error message means. I'm just wondering why my system runs on one up to version 2.1.0 without problems and now not anymore. Maybe you have an idea. Maybe I have to adjust the settings somewhere or something

**Comment by ghdi** [comment] 2021-05-16 02:39
I experienced a similar issue after upgrading from 2.1.0 to 2.2.0:

[AbstractClassMetadataFactory.php:80] Doctrine\Persistence\Mapping\AbstractClassMetadataFactory::setCacheDriver is deprecated. Use setCache() with a PSR-6 cache instead

This seems to be triggered by doctrine/orm (2.8.4):

/Doctrine/ORM/EntityManager.php:        $this->metadataFactory->setCacheDriver($this->config->getMetadataCacheImpl());

**Comment by greg0ire** [comment] 2021-05-16 06:38
@ariesprodesign I was not trying to explain to you what the error message means, but to voice the question you should ask yourself: "What is it then?"

Please find out however you can. One way to do so is as follows.

```diff
         if (! $cacheDriver instanceof CacheProvider) {
+           var_dump(get_class($cacheDriver));
             throw new BadMethodCallException('Cannot convert cache to PSR-6 cache');
        }
```


You can try that too @ghdi .

This looks like the issue is linked to https://github.com/doctrine/persistence/pull/144

> Note that if you use a custom implementation of doctrine/cache, the library may not be able to provide a forward compatibility layer. The cache implementation MUST extend the `Doctrine\Common\Cache\CacheProvider` class.

This is probably your case.

**Comment by ghdi** [comment] 2021-05-16 06:59
As I mentioned, the error is triggered by the entityManager (Doctrine/ORM/EntityManager), because it calls **setChacheDriver** which has been deprecated in Doctrine/Persistence 2.2.0 (/Doctrine/Persistence/Mapping/AbstractClassMetadataFactory)

In AbstractClassMetadataFactory , setCacheDriver has been set to trigger an error:

`public function setCacheDriver(?Cache $cacheDriver = null)
{
@trigger_error(sprintf('%s is deprecated. Use setCache() with a PSR-6 cache instead.', __METHOD__), E_USER_DEPRECATED);`

In doctrine/orm 2.8.4, the entityManager calls **setCacheDriver**, hence triggering the error:

`protected function __construct(Connection $conn, Configuration $config, EventManager $eventManager)
    {
        $this->conn         = $conn;
        $this->config       = $config;
        $this->eventManager = $eventManager;
        $metadataFactoryClassName = $config->getClassMetadataFactoryName();
        $this->metadataFactory = new $metadataFactoryClassName();
        $this->metadataFactory->setEntityManager($this);
        $this->metadataFactory->setCacheDriver($this->config->getMetadataCacheImpl());
        $this->repositoryFactory = $config->getRepositoryFactory();
`

**Comment by greg0ire** [comment] 2021-05-16 07:30
> setCacheDriver has been set to trigger an error

I know it's called `trigger_error`, but as you can see:
1. The error is silenced with `@`;
2. The second argument is `E_USER_DEPRECATED`.

This is supposed to produce a deprecation warning, not to break your application (and as you can see, it doesn't, the exception that is below does).

So I'll ask one more time: `setCacheDriver()` does not seem to be called with a `CacheProvider` instance. What is it called with?

**Comment by ariesprodesign** [comment] 2021-05-17 07:29
Neos\Flow\Persistence\Doctrine\CacheAdapter I work with Neos.Flow. Maybe they have to adjust that. I ask the guys from Neos.Flow. I think the problem is not yours. We are sorry

**Comment by ariesprodesign** [comment] 2021-05-17 07:30
And thank you very much

**Comment by greg0ire** [comment] 2021-05-17 10:15
>  I think the problem is not yours.

It kind of is, it's a documented BC-break though (which means we will not fix the issue although we did create it). The solution will be to have Neos\Flow\Persistence\Doctrine\CacheAdapter extend https://github.com/doctrine/cache/blob/2.0.x/lib/Doctrine/Common/Cache/CacheProvider.php

**Comment by albe** [comment] 2021-05-17 13:53
Thanks for the hint @greg0ire! We'll have that covered and this issue can be closed :)

**Comment by flaushi** [comment] 2021-05-17 16:26
Hmm, not sure what to do now.
I am not using any neos lib, but still get few thousand deprecations 
```
Doctrine\Persistence\Mapping\AbstractClassMetadataFactory::setCacheDriver is deprecated. Use setCache() with a PSR-6 cache instead.
```
do I have to downgrade to 2.1.1?

**Comment by greg0ire** [comment] 2021-05-17 17:27
@flaushi no, you have to use `setCache()` If you use `SYMFONY_DEPRECATIONS_HELPER=/setCacheDriver/`, you should be able to see where it is actually called (because odds are you are not calling it yourself directly, but through another software layer).

**Comment by greg0ire** [comment] 2021-05-17 20:09
@deguif has found and fixed an occurence of this at https://github.com/doctrine/orm/pull/8698

**Comment by alcaeus** [comment] 2021-05-18 12:58
Will be fixed by #182 in combination with doctrine/cache#370.

**Closed as completed** 2021-05-19 07:07 UTC

**Comment by ghdi** [comment] 2021-05-20 10:18
greg0ire, 

2.2.1 fixed the issue for me, very much appreciate the effort!

**Comment by greg0ire** [comment] 2021-05-20 16:50
Well thank @alcaeus instead, he did all the work, I merely clicked buttons here :slightly_smiling_face:
